name: CI
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install
      - run: npm run build
      # - run: mkdir -p build

      - name: Generate Contributors Images
        uses: jaywcjlove/github-action-contributors@main
        id: contributors

      - name: Overwrite test/overwrite.file.md
        # uses: github-action-modify-file-content@main
        uses: ./
        with:
          path: test/overwrite.file.md
          body: "{{date:YYYY-MM-DD HH:mm:ss}}"
          overwrite: 'true'

      - name: Modify test test/overwrite.file.md
        # uses: jaywcjlove/github-action-modify-file-content@main
        uses: ./
        with:
          branch: test
          path: test/overwrite.file.md
          body: "{{date:YYYY-MM-DD HH:mm:ss}}"
          overwrite: 'true'

      - name: Modify README.md
        # uses: jaywcjlove/github-action-modify-file-content@main
        uses: ./
        with:
          path: README.md
          body: "{{date:YYYY-MM-DD HH:mm:ss}}"

      - name: Modify README.md
        # uses: jaywcjlove/github-action-modify-file-content@main
        uses: ./
        with:
          openDelimiter: '<!--GAMFC_TABEL-->'
          closeDelimiter: '<!--GAMFC_TABEL-END-->'
          path: README.md
          body: "different `GAMFC_TABEL` & `GAMFC_TABEL-END` (test)"


      - name: Modify CONTRIBUTING
        uses: jaywcjlove/github-action-modify-file-content@main
        with:
          path: README.md
          openDelimiter: '<!--CONTRIBUTING-->'
          closeDelimiter: '<!--CONTRIBUTING-END-->'
          body: |

            
            ${{steps.contributors.outputs.htmlList}}

      # - name: Converts Markdown to HTML
      #   uses: jaywcjlove/markdown-to-html-cli@main
      #   with:
      #     output: build/index.html
      #     github-corners: https://github.com/jaywcjlove/github-action-modify-file-content
      #     favicon: data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🏷️</text></svg>

      - name: Create idoc config
        run: |
          cat > idoc.yml << EOF
          site: "Modify File Content {{version}}"
          menus:
            Home: index.html
            Apps: 
              url: https://jaywcjlove.github.io/#/app
              target: __blank
            Sponsor: 
              url: https://jaywcjlove.github.io/#/sponsor
              target: __blank
          footer: |
            <a href="https://jaywcjlove.github.io/#/sponsor" target="_blank">Sponsor</a> • 
            <a href="https://jaywcjlove.github.io/create-tag-action" target="_blank">Create Tag</a> • 
            <a href="https://jaywcjlove.github.io/github-action-contributors" target="_blank">Contributors</a> • 
            <a href="https://jaywcjlove.github.io/github-action-read-file" target="_blank">Read File Content</a> • 
            <a href="https://jaywcjlove.github.io/generated-badges" target="_blank">Generated Badges</a>
            <br />
            Released under the MIT License. Copyright © {{idocYear}} Kenny Wong<br />
            Generated by <a href="https://github.com/jaywcjlove/idoc" target="_blank">idoc</a> v{{idocVersion}}
          
          EOF
  
      - run: npm install idoc@1 -g
      - run: idoc
  
      - name: Is a tag/release created auto? 
        id: create_tag
        uses: jaywcjlove/create-tag-action@main
        with:
          # test: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'
          package-path: ./package.json

      - name: get tag version
        id: tag_version
        uses: jaywcjlove/changelog-generator@main

      - name: gh-pages README.md
        working-directory: dist
        run: |
          cat > README.md << EOF
          Website: https://jaywcjlove.github.io/github-action-modify-file-content  

          TEST: <!--GAMFC-->2022-11-29 01:44:16<!--GAMFC-END-->
          EOF

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          commit_message: ${{steps.tag_version.outputs.tag}} ${{ github.event.head_commit.message }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

      - name: Generate Changelog
        id: changelog
        uses: jaywcjlove/changelog-generator@main
        with:
          head-ref: ${{steps.create_tag.outputs.version}}
          filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'

      - name: Create Release
        uses: jaywcjlove/create-tag-action@main
        with:
          # test: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'
          package-path: ./package.json
          release: true
          body: |
            [![Buy me a coffee](https://img.shields.io/badge/Buy%20me%20a%20coffee-048754?logo=buymeacoffee)](https://jaywcjlove.github.io/#/sponsor) 

            Documentation ${{ steps.changelog.outputs.tag }}: https://raw.githack.com/jaywcjlove/github-action-modify-file-content/${{ steps.changelog.outputs.gh-pages-short-hash }}/index.html  
            Comparing Changes: ${{ steps.changelog.outputs.compareurl }} 

            ${{ steps.changelog.outputs.changelog }}

            ```yml
            - name: Modify README.md
              uses: jaywcjlove/github-action-modify-file-content@main
              with:
                path: README.md
            ```

            `README.md` file content

            ```markdown
            update time <!--GAMFC-->2022-10-26 14:39:35<!--GAMFC-END-->
            ```

            Replace the content between `<!--GAMFC-->` and 
            `<!--GAMFC-END-->`.