name: test
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: npm install
      - run: npm run build
      - run: mkdir -p build

      - name: Overwrite test/overwrite.file.md
        # uses: github-action-modify-file-content@main
        uses: ./
        with:
          path: test/overwrite.file.md
          body: "{{date:YYYY-MM-DD HH:mm:ss}}"
          overwrite: 'true'

      - name: Modify README.md
        # uses: github-action-modify-file-content@main
        uses: ./
        with:
          path: README.md
          body: "{{date:YYYY-MM-DD HH:mm:ss}}"

      - name: Modify README.md
        # uses: github-action-modify-file-content@main
        uses: ./
        with:
          openDelimiter: '<!--GAMFC_TABEL-->'
          closeDelimiter: '<!--GAMFC_TABEL-END-->'
          path: README.md
          body: "different `GAMFC_TABEL` & `GAMFC_TABEL-END` (test)"

      - name: Converts Markdown to HTML
        uses: jaywcjlove/markdown-to-html-cli@main
        with:
          output: build/index.html
          github-corners: https://github.com/jaywcjlove/github-action-modify-file-content
          favicon: data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🏷️</text></svg>


      - name: Is a tag/release created auto? 
        id: create_tag
        uses: jaywcjlove/create-tag-action@main
        with:
          # test: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'
          package-path: ./package.json

      - name: get tag version
        id: tag_version
        uses: jaywcjlove/changelog-generator@main

      - name: gh-pages README.md
        working-directory: build
        run: |
          cat > README.md << EOF
          Website: https://jaywcjlove.github.io/github-action-modify-file-content  

          TEST: <!--GAMFC-->2022-11-29 01:44:16<!--GAMFC-END-->
          EOF

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          commit_message: ${{steps.tag_version.outputs.tag}} ${{ github.event.head_commit.message }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build

      - name: Modify gh-pages README.md
        # uses: github-action-modify-file-content@main
        uses: ./
        with:
          path: README.md
          branch: gh-pages
          body: "{{date:YYYY-MM-DD HH:mm:ss}}"

      - name: Generate Changelog
        id: changelog
        uses: jaywcjlove/changelog-generator@main
        with:
          head-ref: ${{steps.create_tag.outputs.version}}
          filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'

      - name: Create Release
        uses: jaywcjlove/create-tag-action@main
        with:
          # test: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'
          package-path: ./package.json
          release: true
          body: |
            Documentation ${{ steps.changelog.outputs.tag }}: https://raw.githack.com/jaywcjlove/github-action-modify-file-content/${{ steps.changelog.outputs.gh-pages-short-hash }}/index.html  
            Comparing Changes: ${{ steps.changelog.outputs.compareurl }} 

            ${{ steps.changelog.outputs.changelog }}

            ```yml
            - name: Modify README.md
              uses: jaywcjlove/github-action-modify-file-content@main
              with:
                path: README.md
            ```

            `README.md` file content

            ```markdown
            update time <!--GAMFC-->2022-10-26 14:39:35<!--GAMFC-END-->
            ```

            Replace the content between `<!--GAMFC-->` and 
            `<!--GAMFC-END-->`.